// Tool file extraction utilities

import { db } from '@/data';
import { getFileTypeFromPath } from './fileHandling';

// Extract file info from tool use messages and create file records
export async function extractAndSaveFiles(
  taskId: string,
  toolName: string,
  toolInput: Record<string, unknown> | undefined,
  toolOutput: string | undefined
): Promise<void> {
  if (!toolInput) return;

  try {
    // Handle Write tool - creates new files
    if (toolName === 'Write' && toolInput.file_path) {
      const filePath = String(toolInput.file_path);
      const fileName = filePath.split('/').pop() || filePath;
      const content = toolInput.content ? String(toolInput.content) : '';
      const preview = content.slice(0, 500);
      const fileType = getFileTypeFromPath(filePath);

      await db.createFile({
        task_id: taskId,
        name: fileName,
        type: fileType,
        path: filePath,
        preview: preview || undefined,
      });
      console.log('[useAgent] Created file record for Write:', fileName);
    }

    // Handle Edit tool - modifies existing files
    if (toolName === 'Edit' && toolInput.file_path) {
      const filePath = String(toolInput.file_path);
      const fileName = filePath.split('/').pop() || filePath;
      const newContent = toolInput.new_string
        ? String(toolInput.new_string)
        : '';
      const fileType = getFileTypeFromPath(filePath);

      await db.createFile({
        task_id: taskId,
        name: `${fileName} (edited)`,
        type: fileType,
        path: filePath,
        preview: newContent.slice(0, 500) || undefined,
      });
      console.log('[useAgent] Created file record for Edit:', fileName);
    }

    // Handle WebFetch tool - captures web content
    if (toolName === 'WebFetch' && toolInput.url) {
      const url = String(toolInput.url);
      const title = url.replace(/^https?:\/\//, '').slice(0, 60);

      await db.createFile({
        task_id: taskId,
        name: title,
        type: 'website',
        path: url,
        preview: toolOutput?.slice(0, 500) || undefined,
      });
      console.log('[useAgent] Created file record for WebFetch:', title);
    }

    // Handle WebSearch tool - captures search results
    if (toolName === 'WebSearch' && toolInput.query) {
      const query = String(toolInput.query);

      await db.createFile({
        task_id: taskId,
        name: `Search: ${query.slice(0, 50)}`,
        type: 'text',
        path: `search://${encodeURIComponent(query)}`,
        preview: toolOutput?.slice(0, 500) || undefined,
      });
      console.log('[useAgent] Created file record for WebSearch:', query);
    }

    // Handle Bash tool
    if (toolName === 'Bash' && toolInput.command) {
      await extractBashFiles(taskId, toolInput, toolOutput);
    }

    // Handle Skill tool
    if (toolName === 'Skill' && toolOutput) {
      await extractSkillFiles(taskId, toolInput, toolOutput);
    }
  } catch (error) {
    console.error('[useAgent] Failed to extract and save file:', error);
  }
}

// Extract files from Bash tool output
async function extractBashFiles(
  taskId: string,
  toolInput: Record<string, unknown>,
  toolOutput: string | undefined
): Promise<void> {
  const command = String(toolInput.command);
  const detectedBashFiles = new Set<string>();

  const filePatterns = [
    /saved?\s+(?:to\s+)?["']?([^\s"']+\.(?:pptx|xlsx|docx|pdf))["']?/i,
    /(?:created|generated|wrote|output)\s+["']?([^\s"']+\.(?:pptx|xlsx|docx|pdf))["']?/i,
    /writeFile\s*\(\s*["']([^"']+\.(?:pptx|xlsx|docx|pdf))["']/i,
    /(\/[^\s"'`\n]+\.(?:pptx|xlsx|docx|pdf))/gi,
    /`([^`]+\.(?:pptx|xlsx|docx|pdf))`/gi,
  ];

  if (toolOutput) {
    for (const pattern of filePatterns) {
      const matches = toolOutput.matchAll(pattern);
      for (const match of matches) {
        const filePath = match[1] || match[0];
        if (filePath && !detectedBashFiles.has(filePath)) {
          detectedBashFiles.add(filePath);
          const fileName = filePath.split('/').pop() || filePath;
          const fileType = getFileTypeFromPath(filePath);

          await db.createFile({
            task_id: taskId,
            name: fileName,
            type: fileType,
            path: filePath,
            preview: `Generated by command: ${command.slice(0, 100)}`,
          });
          console.log(
            '[useAgent] Created file record for generated file:',
            fileName
          );
        }
      }
    }
  }
}

// Extract files from Skill tool output
async function extractSkillFiles(
  taskId: string,
  toolInput: Record<string, unknown>,
  toolOutput: string
): Promise<void> {
  const filePatterns = [
    /(?:saved?|created|generated|wrote|output)\s+(?:to\s+)?["']?([^\s"'\n]+\.(?:pptx|xlsx|docx|pdf|png|jpg|html))["']?/gi,
    /(?:file|output|presentation|document):\s*["']?([^\s"'\n]+\.(?:pptx|xlsx|docx|pdf|png|jpg|html))["']?/gi,
    /(\/[^\s"'`\n]+\.(?:pptx|xlsx|docx|pdf))/gi,
    /`([^`]+\.(?:pptx|xlsx|docx|pdf))`/gi,
    /(\/[^\s"'\n]*[\u4e00-\u9fff][^\s"'\n]*\.(?:pptx|xlsx|docx|pdf))/gi,
  ];

  const detectedFiles = new Set<string>();

  for (const pattern of filePatterns) {
    const matches = toolOutput.matchAll(pattern);
    for (const match of matches) {
      const filePath = match[1] || match[0];
      if (filePath && !detectedFiles.has(filePath)) {
        detectedFiles.add(filePath);
        const fileName = filePath.split('/').pop() || filePath;
        const fileType = getFileTypeFromPath(filePath);

        await db.createFile({
          task_id: taskId,
          name: fileName,
          type: fileType,
          path: filePath,
          preview: `Generated by skill: ${toolInput.skill || 'unknown'}`,
        });
        console.log(
          '[useAgent] Created file record from Skill output:',
          fileName
        );
      }
    }
  }
}
