export { HomePage } from './Home';
export { TaskDetailPage } from './TaskDetail';
export { LibraryPage } from './Library';
export { SetupPage } from './Setup';
export { DashboardPage } from './dashboard/DashboardPage';
export { BoardPage } from './board/BoardPage';
export { SkillsPage } from './skills/SkillsPage';
export { McpPage } from './mcp/McpPage';
export { ProjectsPage } from './projects/ProjectsPage';
